config/routes.rb
CVSuploader::Application.routes.draw do

    root to: 'products#index'

    resources :products do
      collection { post :import }
    end

end

app/models/product.rb
class Product < ActiveRecord::Base

   

   def self.import(file)
      allowed_attributes = ["id","name","released_on","price","create_at","updated_at"]
      spreadsheet = open_spreadsheet(file)
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).each do |i|
         row=Hash[[header,spreadsheet.row(i)].transpose]
         product = find_by_id(row["id"]) || new
         product.attributes = row.to_hash.select {|k,v| allowed_attributes.include? k }
         product.save!
      end
   end

   def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when '.csv' then Roo::Csv.new(file.path)
      when '.xls' then Roo::Excel.new(file.path, nil, :ignore)
      when '.xlsx' then Roo::Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
      end
   end


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|

      #這一行是標題行
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.order(:name)
    respond_to do |format|
      format.html
      format.csv { send_data @products.to_csv }
      format.xls { send_data @products.to_csv(col_sep: "\t") }
    end
  end


	def import
		Product.import(params[:file])
		redirect_to root_url, noice: "Products imported."
	end


	private

	#rails4 之後的安全設定
    def product_params
      params.require(:product).permit(:name,:price,:released_on)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CVSuploader</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h2>Products</h2>

<%= form_tag import_products_path, multipart: true do %>
	<%= file_field_tag :file %>
	<%= submit_tag "Import" %>
<% end %>


<p>
  Download:
  <%= link_to "CSV", products_path(format: "csv") %> |
  <%= link_to "Excel", products_path(format: "xls") %>
</p>


<p>
	<table>
		  <tr>
		    <th>ID</th>
		    <th>Product Name</th>
		    <th>Price</th>
		    <th>Release Date</th>
		  </tr>
		<% @products.each do |product| %>
			<tr>
				<td><%= product.id %></td>
				<td><%= product.name %></td>
				<td><%= product.price %></td>
				<td><%= product.released_on %></td>
			</tr>
		<% end %>
	</table>
</p>

app/views/products/index.xls.erb
<？XML version="1.0"?> 
<Workbook  xmlns = " urn:schemas-microsoft-com:office:spreadsheet "
   xmlns:o = " urn:schemas-microsoft-com:office:office "
   xmlns:x = " urn:schemas-microsoft-com:office:excel "
   xmlns:ss = " urn:schemas-microsoft-com:office:spreadsheet "
   xmlns:html = " http://www.w3.org/TR/REC-html40 " > 
  <Worksheet  ss:Name = " Sheet1 " > 
    <Table> 
      <Row> 
        <Cell> <Data  ss:Type = " String " > ID </Data> </Cell> 
        <Cell> <Data  ss:Type = " String " > Name </Data> </Cell> 
        <Cell> <Data  ss:Type = " String " > Price </Data> </Cell> 
        <Cell> <Data  ss:Type = " String " > Release Date </Data> </Cell> 
      </Row> 
    <%  @products .each do |product| %>
       <Row> 
        <Cell> <Data  ss:Type = " Number " > <%= product.id %> </Data> </Cell> 
        <Cell> <Data  ss:Type = " String " > <%= product.name %> </Data> </Cell> 
        <Cell> <Data  ss:Type = " Number " > <%= product.price %> </Data> </Cell> 
        <Cell> <Data  ss:Type = " String " > <%= product.released_on %> </Data> </Cell> 
      </Row> 
    <%  end  %>
     </Table> 
  </Worksheet> 
</Workbook>